### ISSUE TITLE
voice detection problem

### ISSUE THREAD

**Issue by vralti07** [Mjrovai/Home-Automation-with-Android-and-NodeMCU#1]
string command not working perfectly please help. i am unable to control the relay via voice commands. i am using the same setup recommended by you to this project.

**Comment by vralti07** [comment]
O comando string não está funcionando perfeitamente, por favor, ajude. Não consigo controlar o relé através de comandos de voz. Estou usando a mesma configuração recomendada por você para este projeto.

**Comment by educ8r** [comment]
hallo Mjrovai..I get some error whenever I click any command button..
Error:com.google.appinventor.components.runtime.Web@d55ff5f,1101,Get,Unable to get a response with the specified URL:http://192.168.0.102/r1on...

but the buttons work properly except for voice not responding..can you please assist? many thanks

**Comment by dchanys** [comment]
My is working if I use only single word to control

**Comment by educ8r** [comment]
Thanks dchanys...🤗

**Comment by saurabhchhaya** [comment]
how and where to install .aia files?

**Comment by osga704** [comment]
Ola amigos estou ancioso em faze lo funcionar mas tambem tenho problemas com o comando de voz alguem encontrou uma solução?

**Comment by vralti07** [comment]
Not yet brother

**Comment by osga704** [comment]
I could understand the reason !! now i made it work like in the video and the problem is that it doesn't work with a newer version of android now we need an update for the latest ones does anyone know how to do it? the voice command and the relays on android 4.4 worked perfectly here
